### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [juliaban/oop-put-course#1]
**Task 1**
- [x] Rename repository to oop-put-course
- [x] Rename file to Task1.java (and main class to Task1)
- [x] Naming of `void count()` function is strange here.

**Task 2**
- [x] Rename file to Task2.java (and main class to Task2)
- [x] Naming of `void flowerInfo())` function could be better e.g. `printFlowersInfo`
